name: Run GitHubGraphQL.R

on:
  schedule:
    - cron: '30 2 * * *'  # Runs at 2:30 AM UTC daily
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-packages-${{ hashFiles('**/*.R') }}
          restore-keys: |
            ${{ runner.os }}-r-packages-

      - name: Install required R packages
        run: |
          Rscript -e "install.packages(c('httr', 'jsonlite', 'ghql'), repos='https://cloud.r-project.org')"

      - name: Run GitHubGraphQL.R
        run: Rscript data-raw/GitHubGraphQL.R
        env:
          myToken: ${{ secrets.DC_PAT }}

      - name: Commit and push updated RData file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/DIG_Issues.RData

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update DIG_Issues.RData [auto commit]"
            git push
          fi
